name: flutter_mapas_osm
description: "Trabalhando com mapas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  battery_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  http: ^1.5.0
  latlong2: ^0.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
